const $=id=>document.getElementById(id);
let stream=null,current=null,db=null,historyStack=[],historyIndex=-1,currentProjectId=null;
const VERSION='32', BACKEND_KEY='carmen_phone_backend_v24',URL_KEY='carmen_last_url_v24',DB_NAME='carmen-phone-v24';
window.addEventListener('error',e=>{try{console.error(e.error||e.message)}catch(_){}});window.addEventListener('unhandledrejection',e=>{try{console.error(e.reason)}catch(_){}});
$('backend').value=localStorage.getItem(BACKEND_KEY)||location.origin;
function toast(s){$('toast').textContent=s;$('toast').classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>$('toast').classList.add('hidden'),3000)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function normalizeUrl(s){s=s.trim();if(!s)return '';if(!/^https?:\/\//i.test(s))return 'https://'+s;return s}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('projects'))d.createObjectStore('projects',{keyPath:'id'});if(!d.objectStoreNames.contains('refs'))d.createObjectStore('refs',{keyPath:'id'});if(!d.objectStoreNames.contains('events'))d.createObjectStore('events',{keyPath:'id'});if(!d.objectStoreNames.contains('leads'))d.createObjectStore('leads',{keyPath:'id'});if(!d.objectStoreNames.contains('queue'))d.createObjectStore('queue',{keyPath:'id'});if(!d.objectStoreNames.contains('sessions'))d.createObjectStore('sessions',{keyPath:'id'});if(!d.objectStoreNames.contains('deepdives'))d.createObjectStore('deepdives',{keyPath:'id'});};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function put(store,v){return new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).put(v);t.oncomplete=()=>res(v);t.onerror=()=>rej(t.error)})}
function all(store){return new Promise((res,rej)=>{const t=db.transaction(store);const r=t.objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function delAll(store){return new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).clear();t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
function openLegacy(name){return new Promise((res,rej)=>{const r=indexedDB.open(name);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);r.onupgradeneeded=()=>{r.transaction.abort();rej(new Error('legacy database does not exist'))}})}
function readFrom(d,store){return new Promise((res,rej)=>{if(!d.objectStoreNames.contains(store))return res([]);const t=d.transaction(store);const q=t.objectStore(store).getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function migrateLegacy(){const marker='carmen_migrated_v18_to_v23';if(localStorage.getItem(marker))return;let old;try{old=await openLegacy('carmen-phone-v18')}catch{localStorage.setItem(marker,'1');return}try{const [projects,refs,events]=await Promise.all([readFrom(old,'projects'),readFrom(old,'refs'),readFrom(old,'events')]);const current=await all('projects');for(const x of projects)if(!current.some(p=>p.id===x.id))await put('projects',x);for(const x of refs)if(!(await all('refs')).some(r=>r.id===x.id))await put('refs',{...x,projectId:x.projectId||projects[0]?.id});for(const x of events)if(!(await all('events')).some(e=>e.id===x.id))await put('events',{...x,projectId:x.projectId||projects[0]?.id});localStorage.setItem(marker,'1');toast('Older Carmen evidence migrated.')}catch(e){console.warn('V18 migration failed',e)}finally{old.close()}}
async function migrateV19(){const marker='carmen_migrated_v19_to_v23';if(localStorage.getItem(marker))return;let old;try{old=await openLegacy('carmen-phone-v19')}catch{localStorage.setItem(marker,'1');return}try{const [projects,refs,events,leads]=await Promise.all([readFrom(old,'projects'),readFrom(old,'refs'),readFrom(old,'events'),readFrom(old,'leads')]);const stores=[['projects',projects],['refs',refs],['events',events],['leads',leads]];for(const [store,items] of stores){const existing=await all(store);for(const x of items)if(!existing.some(y=>y.id===x.id))await put(store,x)}localStorage.setItem(marker,'1');toast('V19 data migrated into V20.')}catch(e){console.warn('V19 migration failed',e)}finally{old.close()}}
async function migrateV20(){const marker='carmen_migrated_v20_to_v23';if(localStorage.getItem(marker))return;let old;try{old=await openLegacy('carmen-phone-v20')}catch{localStorage.setItem(marker,'1');return}try{const [projects,refs,events,leads]=await Promise.all([readFrom(old,'projects'),readFrom(old,'refs'),readFrom(old,'events'),readFrom(old,'leads')]);for(const x of projects)await put('projects',x);for(const x of refs)await put('refs',x);for(const x of events)await put('events',x);for(const x of leads)await put('leads',x);localStorage.setItem(marker,'1');toast('V20 data migrated into V23.')}catch(e){console.warn('V20 migration failed',e)}finally{old.close()}}
async function migrateV23(){const marker='carmen_migrated_v23_to_v24';if(localStorage.getItem(marker))return;let old;try{old=await openLegacy('carmen-phone-v23')}catch{localStorage.setItem(marker,'1');return}try{const [projects,refs,events,leads,queue]=await Promise.all([readFrom(old,'projects'),readFrom(old,'refs'),readFrom(old,'events'),readFrom(old,'leads'),readFrom(old,'queue')]);for(const x of projects)await put('projects',x);for(const x of refs)await put('refs',x);for(const x of events)await put('events',x);for(const x of leads)await put('leads',x);for(const x of queue)await put('queue',x);localStorage.setItem(marker,'1');toast('V23 data migrated into V24.')}catch(e){console.warn('V23 migration failed',e)}finally{old.close()}}
async function migrateV22(){const marker='carmen_migrated_v22_to_v23';if(localStorage.getItem(marker))return;let old;try{old=await openLegacy('carmen-phone-v22')}catch{localStorage.setItem(marker,'1');return}try{const [projects,refs,events,leads,queue]=await Promise.all([readFrom(old,'projects'),readFrom(old,'refs'),readFrom(old,'events'),readFrom(old,'leads'),readFrom(old,'queue')]);for(const x of projects)await put('projects',x);for(const x of refs)await put('refs',x);for(const x of events)await put('events',x);for(const x of leads)await put('leads',x);for(const x of queue)await put('queue',x);localStorage.setItem(marker,'1');toast('V22 data migrated into V23.')}catch(e){console.warn('V22 migration failed',e)}finally{old.close()}}
async function migrateV21(){const marker='carmen_migrated_v21_to_v23';if(localStorage.getItem(marker))return;let old;try{old=await openLegacy('carmen-phone-v21')}catch{localStorage.setItem(marker,'1');return}try{const [projects,refs,events,leads]=await Promise.all([readFrom(old,'projects'),readFrom(old,'refs'),readFrom(old,'events'),readFrom(old,'leads')]);for(const x of projects)await put('projects',x);for(const x of refs)await put('refs',x);for(const x of events)await put('events',x);for(const x of leads)await put('leads',x);localStorage.setItem(marker,'1');toast('V21 data migrated into V23.')}catch(e){console.warn('V21 migration failed',e)}finally{old.close()}}
async function ensureProject(){let ps=await all('projects');if(!ps.length){const p={id:'project_'+crypto.randomUUID(),name:'My first investigation',question:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await put('projects',p);ps=[p]}currentProjectId=currentProjectId&&ps.some(p=>p.id===currentProjectId)?currentProjectId:ps[0].id;renderProjects(ps);$('projectQuestion').value=ps.find(p=>p.id===currentProjectId)?.question||'';await refresh()}
function renderProjects(ps){$('projectSelect').innerHTML=ps.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('projectSelect').value=currentProjectId}
function sourceTypeLabel(v){return ({adult_video:'Adult video',reddit:'Reddit',web:'Web',other:'Other'}[v]||'Web')}
function currentSourceType(){return $('sourceType')?.value||'web'}
async function refresh(){const refs=await all('refs'),events=await all('events'),allLeads=await all('leads');const projectRefs=refs.filter(r=>r.projectId===currentProjectId),projectLeads=allLeads.filter(x=>x.projectId===currentProjectId);$('refs').textContent=projectRefs.length;$('events').textContent=events.filter(e=>e.projectId===currentProjectId).length;const p=buildPatterns(projectRefs);$('patterns').textContent=p.length;renderPatternBoard(projectRefs);renderArchive(projectRefs);renderSourceStats(projectRefs);renderDashboard(projectRefs);const queue=(await all('queue')).filter(q=>q.projectId===currentProjectId);$('queueCount').textContent=queue.filter(q=>q.status==='queued').length;renderQueue(queue);$('projectCount').textContent=`${projectRefs.length} evidence item${projectRefs.length===1?'':'s'}`;renderLeads(projectLeads);renderDeepDive(projectRefs);renderEvidenceGraph();renderIntelligence();
  renderWorkspace();const next=projectLeads.find(l=>l.status==='new');$('nextMove').textContent=next?`Review this lead: ${next.text}`:queue.some(q=>q.status==='queued')?`Open the next queued source: ${queue.find(q=>q.status==='queued')?.label||'research item'}.`:projectRefs.length<2?'Capture another piece of evidence so Carmen can compare them.':p.length?'Compare evidence around one of the recurring patterns.':'Analyze more evidence to build recurring patterns.'}
function patternKey(s){return String(s||'').toLowerCase().replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim()}
function patternTokens(s){return new Set(patternKey(s).split(' ').filter(w=>w.length>2&&!['the','and','with','that','this','from','visible','appears','likely','possibly'].includes(w)))}
function similarity(a,b){const A=patternTokens(a),B=patternTokens(b);if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/(A.size+B.size-hit)}
function buildPatterns(refs){const groups=[];for(const r of refs){for(const raw of (r.candidatePatterns||[])){const label=String(raw.text||raw).trim();if(!label)continue;let g=groups.find(x=>similarity(x.label,label)>=.62);if(!g){g={label,support:0,evidenceIds:new Set(),firstSeen:r.createdAt,lastSeen:r.createdAt};groups.push(g)}g.support++;g.evidenceIds.add(r.id);if(r.createdAt<g.firstSeen)g.firstSeen=r.createdAt;if(r.createdAt>g.lastSeen)g.lastSeen=r.createdAt}}return groups.map(g=>({...g,evidenceIds:[...g.evidenceIds],evidenceCount:g.evidenceIds.size,confidence:g.evidenceIds.size>=3?'strong recurring':g.evidenceIds.size>=2?'recurring':'emerging'})).sort((a,b)=>b.evidenceCount-a.evidenceCount||b.support-a.support)}
function renderPatternBoard(refs){const ps=buildPatterns(refs);$('patternBoard').innerHTML=ps.map(p=>`<div class="pattern"><b>${esc(p.label)}</b> <span class="badge">${esc(p.confidence)}</span><div class="patternbar"><span style="width:${Math.min(100,p.evidenceCount/Math.max(1,refs.length)*100)}%"></span></div><small>${p.evidenceCount} of ${refs.length} evidence items support this hypothesis · ${p.support} mentions</small></div>`).join('')||'<span class="muted">No recurring pattern hypotheses yet. Analyze more evidence to build the board.</span>';return ps}
function renderArchive(refs){const q=String($('archiveSearch')?.value||'').trim().toLowerCase();const filtered=!q?refs:refs.filter(r=>[r.title,r.url,r.context,r.signature,...(r.observations||[]).map(x=>x.text||x),...(r.candidatePatterns||[]).map(x=>x.text||x)].join(' ').toLowerCase().includes(q));$('archive').innerHTML=filtered.slice().reverse().map(r=>`<label class="refitem"><input type="checkbox" class="refcheck" value="${esc(r.id)}"><span><b>${esc(r.title||r.url||r.id)}</b> <span class="badge">${esc(r.source||'capture')}</span><br><small>${new Date(r.createdAt).toLocaleString()}${r.url?' · '+esc(r.url):''}</small><br>${(r.observations||[]).slice(0,2).map(x=>esc(x.text||x)).join(' · ')||esc(r.context||'')}</span></label>`).join('')||'<span class="muted">No matching evidence in this investigation.</span>'}
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function backfillFingerprints(){const refs=await all('refs');for(const r of refs){if(!r.fingerprint&&r.imageDataUrl){r.fingerprint=await sha(r.imageDataUrl);await put('refs',r)}}}
function evidenceHealth(refs){const n=refs.length;if(!n)return {score:0,label:'No evidence yet',tips:['Capture your first reference.']};let score=0;const typed=refs.filter(r=>r.sourceType).length;const contextual=refs.filter(r=>String(r.context||'').trim()).length;const analyzed=refs.filter(r=>Array.isArray(r.observations)&&r.observations.length).length;score=Math.round((typed/n*.25+contextual/n*.2+analyzed/n*.35+Math.min(1,n/5)*.2)*100);let tips=[];if(typed<n)tips.push(`${n-typed} reference${n-typed===1?'':'s'} missing a source type.`);if(contextual<n)tips.push('Add context or a research question to more captures.');if(analyzed<n)tips.push('Analyze more saved captures.');if(n<5)tips.push(`Add ${5-n} more reference${5-n===1?'':'s'} for a stronger comparison set.`);return {score,label:score>=80?'Strongly documented':score>=55?'Developing':'Needs more documentation',tips}}
function renderDashboard(refs){const h=evidenceHealth(refs);const box=$('evidenceHealth');if(box)box.innerHTML=`<div class=\"stat\"><div><div class=\"num\">${h.score}%</div><small>Documentation</small></div><div><div class=\"num\">${refs.filter(r=>r.sourceType).length}</div><small>Typed sources</small></div><div><div class=\"num\">${refs.filter(r=>Array.isArray(r.observations)&&r.observations.length).length}</div><small>Analyzed</small></div></div><p><b>${esc(h.label)}</b></p><small>${h.tips.map(esc).join(' · ')}</small>`;const timeline=$('timeline');if(timeline)timeline.innerHTML=refs.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,8).map(r=>`<div class=\"pattern\"><b>${esc(r.title||r.url||'Evidence')}</b> <span class=\"badge\">${esc(sourceTypeLabel(r.sourceType||'web'))}</span><br><small>${new Date(r.createdAt).toLocaleString()} · ${esc(r.sourceName||queueDomain(r.url)||'source')}</small></div>`).join('')||'<span class=\"muted\">Your recent evidence timeline will appear here.</span>'}
function sourceStats(refs){const m={};for(const r of refs){const type=sourceTypeLabel(r.sourceType||'web'),name=r.sourceName||queueDomain(r.url)||'Unknown source';const k=type+'|'+name;if(!m[k])m[k]={type,name,count:0,last:r.createdAt};m[k].count++;if(r.createdAt>m[k].last)m[k].last=r.createdAt}return Object.values(m).sort((a,b)=>b.count-a.count)}
function renderSourceStats(refs){const box=$('sourceStats');if(!box)return;const rows=sourceStats(refs);box.innerHTML=rows.map(x=>`<div class=\"pattern\"><b>${esc(x.name)}</b> <span class=\"badge\">${esc(x.type)}</span><br><small>${x.count} evidence item${x.count===1?'':'s'} · last captured ${new Date(x.last).toLocaleString()}</small></div>`).join('')||'<span class=\"muted\">No source statistics yet.</span>'}
function queueDomain(u){try{return new URL(normalizeUrl(u)).hostname.replace(/^www\./,'')}catch{return ''}}
function renderQueue(items){const box=$('queueList');if(!box)return;const f=$('queueFilter')?.value||'all';const arr=items.filter(x=>f==='all'||x.status===f).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));box.innerHTML=arr.map(x=>`<div class=\"lead\"><div><b>${esc(x.label||x.url)}</b> <span class=\"badge\">${esc(x.status)}</span> <span class=\"badge\">${esc(sourceTypeLabel(x.sourceType))}</span></div><small>${esc(queueDomain(x.url))}${x.note?' · '+esc(x.note):''}</small><div class=\"row\" style=\"margin-top:8px\"><button data-queue=\"open\" data-id=\"${esc(x.id)}\">Open</button><button data-queue=\"done\" data-id=\"${esc(x.id)}\">${x.status==='completed'?'Re-queue':'Mark done'}</button><button data-queue=\"delete\" data-id=\"${esc(x.id)}\">Remove</button></div></div>`).join('')||'<span class=\"muted\">No research items in this queue.</span>'}
async function addQueue(){const url=normalizeUrl($('queueUrl').value);if(!url)return toast('Enter a URL first.');const q={id:'queue_'+crypto.randomUUID(),projectId:currentProjectId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),url,label:$('queueLabel').value.trim()||queueDomain(url),sourceType:$('queueSourceType').value,note:$('queueNote').value.trim(),status:'queued'};await put('queue',q);$('queueUrl').value='';$('queueLabel').value='';$('queueNote').value='';await (async()=>{try{await openDB();await refresh()}catch(e){console.error(e);toast('Carmen storage could not be opened. Try reloading the app.')}})();toast('Added to research queue.')}
$('queueAdd').onclick=addQueue;$('queueFilter').onchange=async()=>renderQueue((await all('queue')).filter(q=>q.projectId===currentProjectId));$('queueList').onclick=async e=>{const b=e.target.closest('[data-queue]');if(!b)return;const id=b.dataset.id,act=b.dataset.queue,qs=await all('queue'),q=qs.find(x=>x.id===id);if(!q)return;if(act==='open'){navigate(q.url);setTab('browse');return}if(act==='done'){q.status=q.status==='completed'?'queued':'completed';q.updatedAt=new Date().toISOString();await put('queue',q)}if(act==='delete'){if(!confirm('Remove this research item from the queue?'))return;await new Promise((res,rej)=>{const t=db.transaction('queue','readwrite');t.objectStore('queue').delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}await refresh()};
function setTab(name){for(const [id,view] of [['tabBrowse','browseView'],['tabEvidence','evidenceView'],['tabArchive','archiveView'],['tabWorkspace','workspaceView'],['tabDeepDive','deepDiveView'],['tabGraph','graphView'],['tabIntelligence','intelligenceView'],['tabLeads','leadsView']]){$(id)?.classList.toggle('active',id.toLowerCase().includes(name));$(view)?.classList.toggle('hidden',view!==name+'View')}for(const id of ['navBrowse','navEvidence','navArchive','navWorkspace','navDeepDive','navGraph','navIntelligence','navLeads'])$(id)?.classList.toggle('active',id.toLowerCase().includes(name))}
$('tabBrowse').onclick=()=>setTab('browse');$('tabEvidence').onclick=()=>setTab('evidence');$('tabArchive').onclick=()=>setTab('archive');$('tabLeads').onclick=()=>setTab('leads');$('tabIntelligence').onclick=()=>setTab('intelligence');$('navIntelligence').onclick=()=>setTab('intelligence');
$('navBrowse').onclick=()=>setTab('browse');$('navEvidence').onclick=()=>setTab('evidence');$('navArchive').onclick=()=>setTab('archive');$('navLeads').onclick=()=>setTab('leads');$('quickCapture').onclick=()=>{setTab('browse');$('pick').click()};$('quickArchive').onclick=()=>setTab('archive');$('quickLeads').onclick=()=>setTab('leads');$('quickCompare').onclick=()=>{setTab('archive');$('researchQuestion').focus()};$('quickIntelligence').onclick=()=>setTab('intelligence');$('importBtn').onclick=()=>$('importFile').click();
$('projectSelect').onchange=async()=>{currentProjectId=$('projectSelect').value;const ps=await all('projects');$('projectQuestion').value=ps.find(p=>p.id===currentProjectId)?.question||'';await refresh()};
$('newProject').onclick=async()=>{const name=prompt('Name this investigation:','New investigation');if(!name?.trim())return;const p={id:'project_'+crypto.randomUUID(),name:name.trim(),question:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await put('projects',p);currentProjectId=p.id;renderProjects(await all('projects'));$('projectQuestion').value='';await refresh();toast('Investigation created.')};
$('renameProject').onclick=async()=>{const ps=await all('projects'),p=ps.find(x=>x.id===currentProjectId);if(!p)return;const name=prompt('Rename investigation:',p.name);if(!name?.trim())return;p.name=name.trim();p.updatedAt=new Date().toISOString();await put('projects',p);renderProjects(await all('projects'));toast('Investigation renamed.')};
$('saveProjectQuestion').onclick=async()=>{const ps=await all('projects'),p=ps.find(x=>x.id===currentProjectId);if(!p)return;p.question=$('projectQuestion').value.trim();p.updatedAt=new Date().toISOString();await put('projects',p);toast('Investigation question saved.')};
function navigate(u,push=true){u=normalizeUrl(u);if(!u)return;$('url').value=u;$('webview').src=u;localStorage.setItem(URL_KEY,u);if(push){historyStack=historyStack.slice(0,historyIndex+1);historyStack.push(u);historyIndex=historyStack.length-1}updateNav()}
function updateNav(){$('back').disabled=historyIndex<=0;$('forward').disabled=historyIndex<0||historyIndex>=historyStack.length-1}
$('go').onclick=()=>navigate($('url').value);$('url').addEventListener('keydown',e=>{if(e.key==='Enter')$('go').click()});$('back').onclick=()=>{if(historyIndex>0){historyIndex--;navigate(historyStack[historyIndex],false)}};$('forward').onclick=()=>{if(historyIndex<historyStack.length-1){historyIndex++;navigate(historyStack[historyIndex],false)}};$('reload').onclick=()=>{$('webview').src=$('webview').src};$('openExternal').onclick=()=>{const u=normalizeUrl($('url').value);if(u)location.href=u};$('webview').addEventListener('load',()=>toast('Page loaded.'));
$('pick').onclick=()=>$('file').click();$('file').onchange=()=>{const f=$('file').files?.[0];if(!f)return;if(f.size>12*1024*1024)return toast('Screenshot is too large. Choose one under 12 MB.');const rd=new FileReader();rd.onload=()=>{current=rd.result;showCurrent();enableCapture();setTab('evidence');toast('Screenshot loaded.')};rd.readAsDataURL(f)};
$('start').onclick=async()=>{try{if(!navigator.mediaDevices?.getDisplayMedia)throw Error('Screen capture is not available here. Use Choose screenshot.');stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:5},audio:false});$('preview').srcObject=stream;$('preview').classList.remove('hidden');$('start').disabled=true;$('snap').disabled=false;$('stop').disabled=false;stream.getVideoTracks()[0].onended=stop}catch(e){toast(e.message)}};
function stop(){if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('preview').srcObject=null;$('preview').classList.add('hidden');$('start').disabled=false;$('snap').disabled=true;$('stop').disabled=true}$('stop').onclick=stop;
$('snap').onclick=()=>{const v=$('preview'),c=$('canvas');const w=Math.min(v.videoWidth||1280,1600),h=Math.round(w*(v.videoHeight||720)/(v.videoWidth||1280));c.width=w;c.height=h;c.getContext('2d').drawImage(v,0,0,w,h);current=c.toDataURL('image/jpeg',.82);showCurrent();enableCapture();setTab('evidence');toast('Frame captured.')};
function enableCapture(){$('analyze').disabled=false;$('save').disabled=false}function showCurrent(){let el=$('captured');if(!el){el=document.createElement('img');el.id='captured';el.className='preview-img';$('capturedWrap').appendChild(el)}el.src=current;el.alt='Current Carmen capture'}function currentUrl(){return normalizeUrl($('url').value)}
async function saveReference(source='iphone-screenshot',data={}){if(!current)return null;const fingerprint=await sha(current);const existing=(await all('refs')).find(r=>r.projectId===currentProjectId&&r.fingerprint===fingerprint);if(existing){toast('This capture is already saved in this investigation.');return existing}const id='ref_'+crypto.randomUUID();const ref={id,projectId:currentProjectId,createdAt:new Date().toISOString(),source,url:currentUrl(),title:data.title||currentUrl(),context:$('context').value,...data,imageDataUrl:current,fingerprint};await put('refs',ref);await put('events',{id:'evt_'+crypto.randomUUID(),projectId:currentProjectId,type:'reference_saved',at:new Date().toISOString(),refId:id});await refresh();return ref}
$('save').onclick=async()=>{if(!current)return toast('Choose or capture a screenshot first.');await saveReference();toast('Saved to this investigation.')};
$('analyze').onclick=async()=>{if(!current)return;const url=$('backend').value.trim().replace(/\/$/,'');if(!url)return toast('Enter the Worker URL first.');localStorage.setItem(BACKEND_KEY,url);$('status').textContent='Carmen is analyzing…';$('analyze').disabled=true;try{const r=await fetch(url+'/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({imageDataUrl:current,pageContext:$('context').value,pageUrl:currentUrl()})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw Error(text||`HTTP ${r.status}`)}if(!r.ok||data.error)throw Error(data.error||`HTTP ${r.status}`);renderAnalysis(data);await saveReference('iphone-screenshot+vision',data);toast('Analyzed and archived.')}catch(e){$('status').textContent='Analysis failed';toast(e.message)}finally{$('analyze').disabled=false;$('status').textContent='Local archive works without a connection.'}};
function list(v){return (v||[]).map(x=>`<div>• ${esc(x.text||x)}</div>`).join('')||'None reported.'}function renderAnalysis(d){$('result').innerHTML=`<div class="claim"><b>${esc(d.title||'Carmen analysis')}</b></div><div class="claim"><b>Observations</b><br>${list(d.observations)}</div><div class="claim"><b>Inferences</b><br>${list(d.inferences)}</div><div class="claim unknown"><b>Unknowns</b><br>${list(d.unknowns)}</div><div class="claim"><b>Relationships</b><br>${list(d.relationships)}</div><div class="claim"><b>Candidate patterns</b><br>${list(d.candidatePatterns)}</div><div class="claim"><b>Signature</b><br>${esc(d.signature||'Not supplied.')}</div>`}
function renderLeads(leads){const box=$('leadList');if(!box)return;const order={new:0,reviewed:1,dismissed:2};leads.sort((a,b)=>(order[a.status]??9)-(order[b.status]??9)||String(b.createdAt).localeCompare(String(a.createdAt)));box.innerHTML=leads.map(l=>`<div class="lead"><div><b>${esc(l.text)}</b> <span class="badge">${esc(l.status)}</span></div><small>${new Date(l.createdAt).toLocaleString()} · ${l.refIds?.length||0} source reference${(l.refIds?.length||0)===1?'':'s'}</small><div class="row" style="margin-top:8px"><button data-lead-action="review" data-id="${esc(l.id)}">${l.status==='reviewed'?'Reviewed':'Mark reviewed'}</button><button data-lead-action="question" data-id="${esc(l.id)}">Use as question</button><button data-lead-action="dismiss" data-id="${esc(l.id)}">Dismiss</button></div></div>`).join('')||'<span class="muted">No research leads yet. Compare evidence to generate leads.</span>'}
async function updateLead(id,patch){const leads=await all('leads'),l=leads.find(x=>x.id===id);if(!l)return;Object.assign(l,patch,{updatedAt:new Date().toISOString()});await put('leads',l);await refresh()}
$('leadList').onclick=async e=>{const b=e.target.closest('[data-lead-action]');if(!b)return;const id=b.dataset.id,action=b.dataset.leadAction,leads=await all('leads'),l=leads.find(x=>x.id===id);if(!l)return;if(action==='review')await updateLead(id,{status:l.status==='reviewed'?'new':'reviewed'});if(action==='dismiss')await updateLead(id,{status:'dismissed'});if(action==='question'){$('researchQuestion').value=l.text;setTab('archive');toast('Lead copied into the comparison question.')}};
$('showNewLeads').onclick=()=>{setTab('leads');$('leadFilter').value='new';applyLeadFilter()};
$('leadFilter').onchange=applyLeadFilter;function applyLeadFilter(){const f=$('leadFilter')?.value;if(!f)return;document.querySelectorAll('.lead').forEach(x=>{const badge=x.querySelector('.badge');x.classList.toggle('hidden',f!=='all'&&badge?.textContent!==f)})}
$('health').onclick=async()=>{const u=$('backend').value.trim().replace(/\/$/,'');if(!u)return toast('Enter Worker URL.');localStorage.setItem(BACKEND_KEY,u);try{const r=await fetch(u+'/health');const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||`HTTP ${r.status}`);$('status').textContent=`Connected · ${j.model||'model'} · research projects ready`;toast('Carmen backend is connected.')}catch(e){$('status').textContent='Connection failed';toast('Could not reach Worker: '+e.message)}};
$('compare').onclick=async()=>{const ids=[...document.querySelectorAll('.refcheck:checked')].map(x=>x.value);if(ids.length<2)return toast('Select at least 2 references.');if(ids.length>4)return toast('Select no more than 4 references.');const refs=await all('refs'),selected=refs.filter(r=>ids.includes(r.id));const url=$('backend').value.trim().replace(/\/$/,'');if(!url)return toast('Enter the Worker URL first.');$('compare').disabled=true;$('compareResult').innerHTML='<p class="muted">Carmen is comparing the selected evidence…</p>';try{const r=await fetch(url+'/synthesize',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:$('researchQuestion').value||$('projectQuestion').value,references:selected})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw Error(text||`HTTP ${r.status}`)}if(!r.ok||data.error)throw Error(data.error||`HTTP ${r.status}`);$('compareResult').innerHTML=`<div class="claim"><b>Summary</b><br>${esc(data.summary||'')}</div><div class="claim"><b>Consistent findings</b><br>${list(data.consistentFindings)}</div><div class="claim"><b>Differences</b><br>${list(data.differences)}</div><div class="claim"><b>Candidate patterns</b><br>${list(data.candidatePatterns)}</div><div class="claim"><b>Leads</b><br>${list(data.leads)}</div><div class="claim unknown"><b>Unknowns</b><br>${list(data.unknowns)}</div>`;for(const raw of (data.leads||[])){const text=String(raw.text||raw).trim();if(text)await put('leads',{id:'lead_'+crypto.randomUUID(),projectId:currentProjectId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),text,status:'new',refIds:ids,question:$('researchQuestion').value||$('projectQuestion').value})}await put('events',{id:'evt_'+crypto.randomUUID(),projectId:currentProjectId,type:'evidence_synthesis',at:new Date().toISOString(),refIds:ids,question:$('researchQuestion').value||$('projectQuestion').value});await refresh();toast('Comparison complete.')}catch(e){$('compareResult').innerHTML='';toast(e.message)}finally{$('compare').disabled=false}};
$('selectAll').onclick=()=>document.querySelectorAll('.refcheck').forEach(x=>x.checked=true);$('clearSelect').onclick=()=>document.querySelectorAll('.refcheck').forEach(x=>x.checked=false);
$('archiveSearch').oninput=async()=>{const refs=(await all('refs')).filter(r=>r.projectId===currentProjectId);renderArchive(refs)};
$('importFile').onchange=async()=>{const f=$('importFile').files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!data||!Array.isArray(data.references))throw Error('That file is not a Carmen archive.');const ps=await all('projects');let project=ps.find(p=>p.id===currentProjectId);for(const r of data.references){if(!r.id)continue;const exists=(await all('refs')).some(x=>x.id===r.id);if(!exists)await put('refs',{...r,projectId:currentProjectId})}for(const l of (data.leads||[])){if(l.id&&!((await all('leads')).some(x=>x.id===l.id)))await put('leads',{...l,projectId:currentProjectId})}for(const q of (data.queue||[])){if(q.id&&!((await all('queue')).some(x=>x.id===q.id)))await put('queue',{...q,projectId:currentProjectId})}for(const e of (data.events||[])){if(e.id&&!((await all('events')).some(x=>x.id===e.id)))await put('events',{...e,projectId:currentProjectId})}for(const d of (data.deepdives||[])){if(d.id&&!((await all('deepdives')).some(x=>x.id===d.id)))await put('deepdives',{...d,projectId:currentProjectId})}await refresh();toast('Archive imported into this investigation.')}catch(e){toast('Import failed: '+e.message)}finally{$('importFile').value=''}};
$('export').onclick=async()=>{const payload={version:Number(VERSION),schema:'carmen-v32',exportedAt:new Date().toISOString(),project:(await all('projects')).find(p=>p.id===currentProjectId),references:(await all('refs')).filter(r=>r.projectId===currentProjectId),leads:(await all('leads')).filter(l=>l.projectId===currentProjectId),events:(await all('events')).filter(e=>e.projectId===currentProjectId),queue:(await all('queue')).filter(q=>q.projectId===currentProjectId),deepdives:(await all('deepdives')).filter(d=>d.projectId===currentProjectId)};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload)],{type:'application/json'}));a.download=`carmen-${currentProjectId}-archive.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('clear').onclick=async()=>{if(!confirm('Clear this investigation archive?'))return;const refs=(await all('refs')).filter(r=>r.projectId===currentProjectId),events=(await all('events')).filter(e=>e.projectId===currentProjectId),leads=(await all('leads')).filter(l=>l.projectId===currentProjectId),deepdives=(await all('deepdives')).filter(d=>d.projectId===currentProjectId);for(const r of refs)await new Promise((res,rej)=>{const t=db.transaction('refs','readwrite');t.objectStore('refs').delete(r.id);t.oncomplete=res;t.onerror=()=>rej(t.error)});for(const l of leads)await new Promise((res,rej)=>{const t=db.transaction('leads','readwrite');t.objectStore('leads').delete(l.id);t.oncomplete=res;t.onerror=()=>rej(t.error)});for(const e of events)await new Promise((res,rej)=>{const t=db.transaction('events','readwrite');t.objectStore('events').delete(e.id);t.oncomplete=res;t.onerror=()=>rej(t.error)});for(const q of (await all('queue')).filter(q=>q.projectId===currentProjectId))await new Promise((res,rej)=>{const t=db.transaction('queue','readwrite');t.objectStore('queue').delete(q.id);t.oncomplete=res;t.onerror=()=>rej(t.error)});for(const d of deepdives)await new Promise((res,rej)=>{const t=db.transaction('deepdives','readwrite');t.objectStore('deepdives').delete(d.id);t.oncomplete=res;t.onerror=()=>rej(t.error)});await refresh();toast('Investigation archive cleared.')};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('install').classList.remove('hidden')});$('install').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};

function deepEsc(s){return esc(s)}
function deepText(x){return String(x?.text??x??'').trim()}
function deepList(items,section,kind){
  const arr=Array.isArray(items)?items:[];
  if(!arr.length)return '<span class="muted">None reported.</span>';
  return arr.map((x,i)=>{
    const text=deepText(x);
    const hazard=String(x?.type||'').toLowerCase().includes('hazard')||String(x?.severity||'').trim().length>0||kind==='hazard';
    const meta=x?.severity?` <span class="badge">${deepEsc(String(x.severity))}</span>`:'';
    return `<div class="deep-item ${hazard?'hazard-item':''}"><div>${hazard?'⚠️ ':'• '}${deepEsc(text)}${meta}</div><div class="branch-actions"><button class="smallbtn branchBtn" data-focus="${deepEsc(text)}" data-kind="${deepEsc(kind||section)}">Explore</button><button class="smallbtn saveSectionBtn" data-text="${deepEsc(text)}" data-section="${deepEsc(section||'section')}" data-kind="${deepEsc(kind||section||'section')}">Save this</button></div></div>`
  }).join('');
}
function renderDeepResult(d){
  if(!d){$('deepResult').innerHTML='';return}
  $('deepResult').innerHTML=`<div class="claim"><b>${deepEsc(d.title||'Deep dive')}</b><div class="branch-actions"><button id="saveDeepResult" class="smallbtn">Save this deep dive</button></div></div>
  <div class="claim"><b>1. Complete deconstruction</b>${deepList(d.deconstruction,'Complete deconstruction','deconstruction')}</div>
  <div class="claim hazard-block"><b>2. Hazards & failure modes</b>${deepList(d.hazards,'Hazards & failure modes','hazard')}</div>
  <div class="claim"><b>3. Safety architecture</b>${deepList(d.safetyArchitecture,'Safety architecture','safety')}</div>
  <div class="claim"><b>4. Physical plausibility</b>${deepList(d.physicalPlausibility,'Physical plausibility','physical')}</div>
  <div class="claim"><b>5. Safer alternatives</b>${deepList(d.alternatives,'Safer alternatives','alternative')}</div>
  <div class="claim"><b>6. Next questions</b>${deepList(d.nextQuestions,'Next questions','question')}</div>
  <div class="claim unknown"><b>Boundary / uncertainty</b>${deepList(d.boundary,'Boundary / uncertainty','boundary')}</div>`;
  bindDeepButtons();
}
function bindDeepButtons(){
  document.querySelectorAll('.branchBtn').forEach(b=>b.onclick=()=>{
    const f=b.dataset.focus||''; const k=b.dataset.kind||'branch';
    $('deepQuestion').value=`Deep dive specifically into this ${k}: ${f}`;
    window.__deepParentId=window.__deepCurrentNodeId||window.__deepParentId||null;
    window.__deepFocus={focus:f,kind:k};
    runDeepDive(f,k);
  });
  document.querySelectorAll('.saveSectionBtn').forEach(b=>b.onclick=()=>saveDeepSection(b.dataset.text,b.dataset.section,b.dataset.kind));
  $('saveDeepResult')?.addEventListener('click',saveDeepCheckpoint);
}
function draftKey(){return `carmen_deepdraft_${currentProjectId||'none'}`}
function saveDeepDraft(){if(!currentProjectId||!$('deepQuestion'))return;localStorage.setItem(draftKey(),JSON.stringify({question:$('deepQuestion').value,referenceId:$('deepRef').value,focus:window.__deepFocus||{focus:'',kind:'root'},parentId:window.__deepParentId||null,savedAt:new Date().toISOString()}))}
function loadDeepDraft(){try{const d=JSON.parse(localStorage.getItem(draftKey())||'null');if(!d)return;if(d.referenceId&&[...$('deepRef').options].some(o=>o.value===d.referenceId))$('deepRef').value=d.referenceId;if(d.question)$('deepQuestion').value=d.question;window.__deepFocus=d.focus||{focus:'',kind:'root'};window.__deepParentId=d.parentId||null}catch{}}
async function runDeepDive(focus='',kind='root'){
  const refId=$('deepRef').value,ref=(await all('refs')).find(r=>r.id===refId);
  if(!ref)return toast('Select a saved reference first.');
  const url=$('backend').value.trim().replace(/\/$/,'');if(!url)return toast('Enter the Worker URL first.');
  saveDeepDraft(); $('deepRun').disabled=true; $('deepResult').innerHTML='<div class="claim">Carmen is exploring this branch…</div>';
  try{
    const r=await fetch(url+'/deepdive',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({imageDataUrl:ref.imageDataUrl,title:ref.title,url:ref.url,sourceType:ref.sourceType,sourceName:ref.sourceName,context:ref.context,analysis:{observations:ref.observations,inferences:ref.inferences,unknowns:ref.unknowns,relationships:ref.relationships,candidatePatterns:ref.candidatePatterns},question:$('deepQuestion').value,focus,focusKind:kind,parentFocus:window.__deepParentId||null})});
    const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw Error(text||`HTTP ${r.status}`)}if(!r.ok||d.error)throw Error(d.error||`HTTP ${r.status}`);
    window.__deepResult=d;window.__deepFocus={focus,kind};renderDeepResult(d);await renderDeepTree();saveDeepDraft();toast('Deep dive complete.');
  }catch(e){$('deepResult').innerHTML='';toast(e.message)}finally{$('deepRun').disabled=false}
}
function nodeTitle(n){return n.title||n.focus||n.question||'Investigation branch'}
function nodeLabel(n){const map={root:'Deep dive',deconstruction:'Deconstruction',hazard:'Hazard',safety:'Safety',physical:'Physical plausibility',alternative:'Alternative',question:'Question',boundary:'Boundary',section:'Saved section'};return map[n.kind]||'Branch'}
async function renderDeepTree(){
  const nodes=(await all('deepdives')).filter(d=>d.projectId===currentProjectId).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));
  const byParent=new Map();nodes.forEach(n=>{const p=n.parentId||'__root__';if(!byParent.has(p))byParent.set(p,[]);byParent.get(p).push(n)});
  const roots=byParent.get('__root__')||[];
  function node(n,depth=0){const children=byParent.get(n.id)||[];return `<div class="tree-node ${depth===0?'root':''}"><div><b>${deepEsc(nodeLabel(n))}</b> <span class="focus">${deepEsc(nodeTitle(n))}</span> <span class="badge">${deepEsc(n.status||'complete')}</span></div><small>${new Date(n.createdAt).toLocaleString()}</small><div class="branch-actions"><button class="loadDeep smallbtn" data-id="${deepEsc(n.id)}">Load</button><button class="continueDeep smallbtn" data-id="${deepEsc(n.id)}">Branch here</button><button class="siblingDeep smallbtn" data-id="${deepEsc(n.id)}">New sibling</button></div>${children.length?`<div class="tree-children">${children.map(x=>node(x,depth+1)).join('')}</div>`:''}</div>`}
  let html=roots.map(r=>node(r)).join('');const orphan=nodes.filter(n=>n.parentId&&!nodes.some(p=>p.id===n.parentId));if(orphan.length)html+=`<div class="tree-node"><b>Recovered / orphaned nodes</b>${orphan.map(n=>node(n,1)).join('')}</div>`;
  $('deepTree').innerHTML=html||'<span class="muted">Nothing saved yet. Run a deep dive, then save the result or any individual section.</span>';
  document.querySelectorAll('.loadDeep').forEach(b=>b.onclick=loadDeepNode);
  document.querySelectorAll('.continueDeep').forEach(b=>b.onclick=async()=>{const n=(await all('deepdives')).find(x=>x.id===b.dataset.id);if(!n)return;$('deepRef').value=n.referenceId;$('deepQuestion').value=`Continue from: ${nodeTitle(n)}`;window.__deepParentId=n.id;window.__deepCurrentNodeId=n.id;window.__deepFocus={focus:n.focus||nodeTitle(n),kind:n.kind||'root'};if(n.result)window.__deepResult=n.result;setTab('deepDive');renderDeepResult(n.result||null);saveDeepDraft()});
  document.querySelectorAll('.siblingDeep').forEach(b=>b.onclick=async()=>{const n=(await all('deepdives')).find(x=>x.id===b.dataset.id);if(!n)return;$('deepRef').value=n.referenceId;$('deepQuestion').value='Explore a new branch alongside: '+nodeTitle(n);window.__deepParentId=n.parentId||null;window.__deepCurrentNodeId=null;window.__deepResult=null;window.__deepFocus={focus:'',kind:'root'};setTab('deepDive');$('deepResult').innerHTML='';saveDeepDraft()});
}
async function loadDeepNode(e){const d=(await all('deepdives')).find(x=>x.id===e.currentTarget.dataset.id);if(!d)return;$('deepRef').value=d.referenceId;$('deepQuestion').value=d.question||'';window.__deepResult=d.result||null;window.__deepFocus={focus:d.focus||'',kind:d.kind||'root'};window.__deepParentId=d.parentId||null;window.__deepCurrentNodeId=d.id;if(d.result)renderDeepResult(d.result);setTab('deepDive');saveDeepDraft()}
async function loadDeepRefs(){const refs=(await all('refs')).filter(r=>r.projectId===currentProjectId);$('deepRef').innerHTML=refs.map(r=>`<option value="${esc(r.id)}">${esc(r.title||r.url||r.id)}</option>`).join('')||'<option value="">No saved references</option>';loadDeepDraft()}
async function saveDeepSection(text,section,kind){
  const refId=$('deepRef').value;if(!refId||!text)return toast('Nothing to save.');
  const id='deep_'+crypto.randomUUID();const item={id,projectId:currentProjectId,createdAt:new Date().toISOString(),referenceId:refId,question:$('deepQuestion').value,result:{title:section,deconstruction:[],hazards:[],safetyArchitecture:[],physicalPlausibility:[],alternatives:[],nextQuestions:[],boundary:[]},focus:text,kind:kind||'section',status:'complete',parentId:window.__deepCurrentNodeId||window.__deepParentId||null};
  if(kind==='hazard')item.result.hazards=[{text}];else if(kind==='safety')item.result.safetyArchitecture=[{text}];else if(kind==='alternative')item.result.alternatives=[{text}];else if(kind==='question')item.result.nextQuestions=[{text}];else if(kind==='physical')item.result.physicalPlausibility=[{text}];else if(kind==='boundary')item.result.boundary=[{text}];else item.result.deconstruction=[{text}];
  await put('deepdives',item);await put('events',{id:'evt_'+crypto.randomUUID(),projectId:currentProjectId,type:'deep_dive_section_saved',at:new Date().toISOString(),deepDiveId:id,parentDeepDiveId:item.parentId||null});window.__deepCurrentNodeId=id;window.__deepParentId=id;await renderDeepTree();toast('Saved as a research node.');
}
async function saveDeepCheckpoint(){
  const refId=$('deepRef').value;if(!refId)return toast('Select a reference first.');if(!window.__deepResult)return toast('Run a deep dive before saving the result.');
  const id='deep_'+crypto.randomUUID();const result=window.__deepResult;const item={id,projectId:currentProjectId,createdAt:new Date().toISOString(),referenceId:refId,question:$('deepQuestion').value,result,focus:window.__deepFocus?.focus||'',kind:window.__deepFocus?.kind||'root',status:'complete',title:result.title||'Deep dive',parentId:window.__deepParentId||null};
  await put('deepdives',item);await put('events',{id:'evt_'+crypto.randomUUID(),projectId:currentProjectId,type:'deep_dive_checkpoint',at:new Date().toISOString(),deepDiveId:id,parentDeepDiveId:item.parentId||null});window.__deepParentId=id;window.__deepCurrentNodeId=id;await renderDeepTree();localStorage.removeItem(draftKey());toast('Saved to the investigation tree.');
}
function graphSourceLabel(n){return ({reference:'Reference',pattern:'Pattern',deepdive:'Deep dive',finding:'Finding',hazard:'Hazard',safety:'Safety',physical:'Physical',alternative:'Alternative',question:'Question',boundary:'Boundary',lead:'Research lead',queue:'Research queue'}[n.type]||'Node')}
async function buildEvidenceGraph(){
  const [refs,deepdives,leads,queue]=await Promise.all([all('refs'),all('deepdives'),all('leads'),all('queue')]);
  const R=refs.filter(x=>x.projectId===currentProjectId),D=deepdives.filter(x=>x.projectId===currentProjectId),L=leads.filter(x=>x.projectId===currentProjectId),Q=queue.filter(x=>x.projectId===currentProjectId);
  const nodes=[],edges=[];const add=(id,type,title,data={})=>{if(!nodes.some(n=>n.id===id))nodes.push({id,type,title:String(title||type),...data})};const edge=(a,b,rel)=>{if(a&&b&&a!==b&&!edges.some(e=>e.a===a&&e.b===b&&e.rel===rel))edges.push({a,b,rel})};
  R.forEach(r=>add('ref:'+r.id,'reference',r.title||r.url||r.id,{refId:r.id,url:r.url,source:r.sourceName||r.sourceType,createdAt:r.createdAt,summary:(r.signature||r.context||'')}));
  const patterns=buildPatterns(R);patterns.forEach(p=>{const id='pattern:'+patternKey(p.label);add(id,'pattern',p.label,{confidence:p.confidence,count:p.evidenceCount});p.evidenceIds.forEach(rid=>edge('ref:'+rid,id,'supports'));});
  D.forEach(d=>{const id='deep:'+d.id;add(id,'deepdive',d.title||nodeTitle(d),{deepId:d.id,focus:d.focus,question:d.question,createdAt:d.createdAt,summary:d.result?.title||''});edge('ref:'+d.referenceId,id,'deep-dives');if(d.parentId)edge('deep:'+d.parentId,id,'branches-to');
    const sections=[['deconstruction','finding'],['hazards','hazard'],['safetyArchitecture','safety'],['physicalPlausibility','physical'],['alternatives','alternative'],['nextQuestions','question'],['boundary','boundary']];
    for(const [key,type] of sections){for(const item of (d.result?.[key]||[])){const text=String(item?.text||item||'').trim();if(!text)continue;const sid=`section:${d.id}:${type}:${text}`;add(sid,type,text,{deepId:d.id,section:key,summary:text});edge(id,sid,'contains');}}
  });
  L.forEach(l=>{const id='lead:'+l.id;add(id,'lead',l.text||'Research lead',{status:l.status,createdAt:l.createdAt,summary:l.text||''});(l.refIds||[]).forEach(rid=>edge('ref:'+rid,id,'raises'));});
  Q.forEach(q=>{const id='queue:'+q.id;add(id,'queue',q.label||q.url,{url:q.url,status:q.status,note:q.note,createdAt:q.createdAt});});
  return {nodes,edges};
}
async function loadDeepNodeById(id){const d=(await all('deepdives')).find(x=>x.id===id);if(!d)return;$('deepRef').value=d.referenceId;$('deepQuestion').value=d.question||'';window.__deepResult=d.result||null;window.__deepFocus={focus:d.focus||'',kind:d.kind||'root'};window.__deepParentId=d.parentId||null;window.__deepCurrentNodeId=d.id;if(d.result)renderDeepResult(d.result);setTab('deepDive');saveDeepDraft()}
function renderWorkspace(){
  const el=document.getElementById('workspacePanel'); if(!el)return;
  const refs=load('refs')||[], leads=load('leads')||[], queue=load('queue')||[], deep=load('deepdives')||[];
  const findings=deep.flatMap(d=>['deconstruction','hazards','safetyArchitecture','physicalPlausibility','alternatives','nextQuestions','boundary'].flatMap(k=>(d.result?.[k]||[]).map(x=>({k,x,d}))));
  const openQ=findings.filter(f=>f.k==='nextQuestions').length;
  const hazards=findings.filter(f=>f.k==='hazards').length;
  const active=deep.filter(d=>!d.completed).length;
  const recent=[...refs].sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,8);
  el.innerHTML=`<div class="card"><div class="eyebrow">INVESTIGATION WORKSPACE</div><h2>What needs attention?</h2><p class="muted">One working surface for evidence, active deep dives, gaps, questions, and the next useful move.</p><div class="statgrid">
  <div class="stat"><b>${refs.length}</b><span>Sources</span></div><div class="stat"><b>${deep.length}</b><span>Deep dives</span></div><div class="stat"><b>${active}</b><span>Active branches</span></div><div class="stat"><b>${hazards}</b><span>Hazards flagged</span></div><div class="stat"><b>${openQ}</b><span>Open questions</span></div><div class="stat"><b>${queue.length}</b><span>Queued</span></div></div></div>
  <div class="card"><div class="sectionhead"><h3>Continue where you left off</h3><button class="secondary" onclick="setTab('deepDive')">Open Deep Dive</button></div>${deep.length?deep.slice(-5).reverse().map(d=>`<div class="workspace-row"><div><b>${esc(d.title||'Untitled deep dive')}</b><div class="muted small">${esc(d.focus||'General investigation')} · ${d.parentId?'Branched investigation':'Root investigation'}</div></div><button class="secondary" onclick="loadDeepNodeById('${d.id}')">Open</button></div>`).join(''):'<div class="empty">No deep dives saved yet.</div>'}</div>
  <div class="card"><div class="sectionhead"><h3>Evidence health</h3><button class="secondary" onclick="setTab('graph')">View graph</button></div><div class="healthgrid"><div><b>Sources</b><span>${refs.length?'Evidence archive is populated.':'Start by capturing a source.'}</span></div><div><b>Leads</b><span>${leads.length?leads.length+' reviewable leads':'No leads recorded.'}</span></div><div><b>Questions</b><span>${openQ?openQ+' questions need resolution':'No open questions surfaced.'}</span></div><div><b>Hazards</b><span>${hazards?hazards+' flagged variables require attention':'No hazards currently surfaced.'}</span></div></div></div>
  <div class="card"><div class="sectionhead"><h3>Recent sources</h3><button class="secondary" onclick="setTab('archive')">Archive</button></div>${recent.length?recent.map(r=>`<div class="workspace-row"><div><b>${esc(r.title||r.url||'Untitled source')}</b><div class="muted small">${esc(r.type||'source')} · ${r.createdAt?new Date(r.createdAt).toLocaleString():''}</div></div></div>`).join(''):'<div class="empty">No saved sources yet.</div>'}</div>
  <div class="card"><div class="sectionhead"><h3>Next useful moves</h3></div><div class="movegrid"><button onclick="setTab('browse')">🌐 Capture source</button><button onclick="setTab('deepDive')">🔬 Start deep dive</button><button onclick="setTab('graph')">🕸️ Trace evidence</button><button onclick="setTab('leads')">🧭 Review leads</button></div></div>`;
}

async function renderEvidenceGraph(){const box=$('graphWorkspace');if(!box)return;const {nodes,edges}=await buildEvidenceGraph();const counts={};nodes.forEach(n=>counts[n.type]=(counts[n.type]||0)+1);const f=$('graphFilter')?.value||'all';const shown=f==='all'?nodes:nodes.filter(n=>n.type===f);const ids=new Set(shown.map(n=>n.id));const relevantEdges=edges.filter(e=>ids.has(e.a)&&ids.has(e.b));$('graphStats').innerHTML=`<div class="stat"><div><div class="num">${nodes.length}</div><small>Nodes</small></div><div><div class="num">${edges.length}</div><small>Connections</small></div><div><div class="num">${counts.reference||0}</div><small>References</small></div><div><div class="num">${counts.deepdive||0}</div><small>Deep dives</small></div></div>`;
  $('graphList').innerHTML=shown.slice().sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).map(n=>{const degree=edges.filter(e=>e.a===n.id||e.b===n.id).length;return `<button class="graph-node" data-graph-id="${esc(n.id)}"><b>${esc(graphSourceLabel(n))}</b> <span class="focus">${esc(n.title)}</span><span class="badge">${degree} link${degree===1?'':'s'}</span>${n.source||n.url?`<small>${esc(n.source||n.url)}</small>`:''}</button>`}).join('')||'<span class="muted">Nothing in the graph yet. Save evidence or a Deep Dive checkpoint to start building the provenance map.</span>';
  $('graphConnections').innerHTML=relevantEdges.slice(0,80).map(e=>`<div class="graph-edge"><b>${esc(nodes.find(n=>n.id===e.a)?.title||e.a)}</b> <span class="badge">${esc(e.rel)}</span> <b>${esc(nodes.find(n=>n.id===e.b)?.title||e.b)}</b></div>`).join('')||'<span class="muted">Choose “All” or a node type with connected nodes to see relationships.</span>';
  document.querySelectorAll('.graph-node').forEach(b=>b.onclick=()=>showGraphNode(b.dataset.graphId,nodes,edges));
}
function showGraphNode(id,nodes,edges){const n=nodes.find(x=>x.id===id);if(!n)return;const related=edges.filter(e=>e.a===id||e.b===id).map(e=>{const other=nodes.find(x=>x.id===(e.a===id?e.b:e.a));return other?`<div class="graph-edge"><span class="badge">${esc(e.rel)}</span> ${esc(other.title)}</div>`:''}).join('');$('graphDetail').innerHTML=`<div class="claim"><b>${esc(graphSourceLabel(n))}</b> <span class="focus">${esc(n.title)}</span><p>${esc(n.summary||n.note||n.url||'No additional summary saved.')}</p>${n.url?`<small>${esc(n.url)}</small>`:''}</div><div><b>Provenance / connections</b>${related||'<p class="muted">No connected nodes.</p>'}</div>`;}
$('graphFilter')?.addEventListener('change',renderEvidenceGraph);$('graphRefresh')?.addEventListener('click',renderEvidenceGraph);
$('intelligenceRefresh')?.addEventListener('click',renderIntelligence);$('intelligenceSave')?.addEventListener('click',saveIntelligenceSnapshot);
async function buildIntelligence(){
  const refs=(await all('refs')).filter(r=>r.projectId===currentProjectId);
  const leads=(await all('leads')).filter(l=>l.projectId===currentProjectId);
  const queue=(await all('queue')).filter(q=>q.projectId===currentProjectId);
  const deep=(await all('deepdives')).filter(d=>d.projectId===currentProjectId);
  const patterns=buildPatterns(refs);
  const graph=await buildEvidenceGraph();
  const findings=deep.filter(d=>d.kind==='deconstruction'||d.kind==='root'||d.kind==='section');
  const questions=[];
  const hazards=[];
  const alternatives=[];
  for(const d of deep){
    for(const x of (d.result?.nextQuestions||[])) { const t=deepText(x); if(t) questions.push({text:t,node:d}); }
    for(const x of (d.result?.hazards||[])) { const t=deepText(x); if(t) hazards.push({text:t,node:d}); }
    for(const x of (d.result?.alternatives||[])) { const t=deepText(x); if(t) alternatives.push({text:t,node:d}); }
  }
  const support=patterns.map(p=>({text:p.text||p.label||String(p),count:p.count||p.refs?.length||1}));
  const weak=support.filter(x=>x.count<=1).slice(0,8);
  const next=[];
  questions.slice(0,6).forEach(q=>next.push({priority:'high',reason:'Open question from a saved Deep Dive',text:q.text}));
  weak.slice(0,4).forEach(x=>next.push({priority:'medium',reason:'Pattern has limited independent support',text:`Test this pattern against another source: ${x.text}`}));
  queue.filter(q=>q.status!=='completed').slice(0,4).forEach(q=>next.push({priority:'medium',reason:'Already queued research',text:q.text||q.title||q.url||'Queued research item'}));
  leads.filter(l=>l.status==='new').slice(0,3).forEach(l=>next.push({priority:'low',reason:'Unreviewed research lead',text:l.text}));
  const contradictions=[];
  const seen=new Map();
  for(const d of deep){
    const vals=[...(d.result?.deconstruction||[]),...(d.result?.physicalPlausibility||[])].map(deepText).filter(Boolean);
    for(const v of vals){const key=v.toLowerCase().replace(/[^a-z0-9 ]/g,'').split(/\s+/).slice(0,10).join(' ');if(key)seen.set(key,(seen.get(key)||0)+1)}
  }
  // Structural contradiction candidates: explicit differences in saved leads/questions, never asserted as factual contradictions.
  const diffLeads=leads.filter(l=>/contradict|conflict|inconsistent|different|disagree/i.test(l.text||''));
  diffLeads.slice(0,6).forEach(l=>contradictions.push(l.text));
  const gaps=[];
  if(!refs.length)gaps.push('No saved evidence yet.');
  if(refs.length===1)gaps.push('Only one source is saved; cross-source corroboration is unavailable.');
  if(questions.length)gaps.push(`${questions.length} open question${questions.length===1?'':'s'} remain in Deep Dive nodes.`);
  if(weak.length)gaps.push(`${weak.length} recurring pattern${weak.length===1?'':'s'} currently have only one recorded support path.`);
  if(!leads.length)gaps.push('No research leads have been generated yet.');
  const confidence=refs.length>=4?'moderate-to-strong':refs.length>=2?'developing':'early';
  return {refs,deep,patterns,support,questions,hazards,alternatives,weak,next,contradictions,gaps,confidence,graphNodes:graph.nodes.length,graphEdges:graph.edges.length,findings};
}
async function renderIntelligence(){
  const box=$('intelligenceWorkspace');if(!box)return;
  const x=await buildIntelligence();
  $('intelStats').innerHTML=`<div class="stat"><div><div class="num">${x.next.length}</div><small>Next moves</small></div><div><div class="num">${x.gaps.length}</div><small>Gaps</small></div><div><div class="num">${x.weak.length}</div><small>Weak patterns</small></div><div><div class="num">${x.questions.length}</div><small>Open questions</small></div></div>`;
  const block=(title,items,empty='Nothing surfaced yet.')=>`<div class="intel-block"><h4>${esc(title)}</h4>${items.length?items.map(i=>`<div class="intel-item">${typeof i==='string'?esc(i):`<b>${esc(i.priority||'')}</b> ${esc(i.text)}`}<small>${typeof i==='string'?'':esc(i.reason||'')}</small></div>`).join(''):`<span class="muted">${esc(empty)}</span>`}</div>`;
  $('intelligenceWorkspace').innerHTML=`<div class="card"><div class="sectionhead"><h3>Investigation signal</h3><span class="badge">${esc(x.confidence)} evidence base</span></div><p class="muted">This layer reasons from Carmen's saved structure. It does not turn weak evidence into certainty. “Contradiction” items are candidates for review, not verdicts.</p>${block('Next investigations',x.next,'No obvious next move. Your investigation may simply need more evidence.')}${block('Evidence gaps',x.gaps)}${block('Potential contradictions',x.contradictions,'No explicit conflict language found in saved leads.')}${block('Under-supported patterns',x.weak.map(w=>`${w.text} — ${w.count} support path${w.count===1?'':'s'}`),'No low-support patterns surfaced.')}${block('Open Deep Dive questions',x.questions.map(q=>q.text),'No open questions surfaced.')}${block('Flagged safety variables',x.hazards.map(h=>'⚠️ '+h.text),'No saved hazards surfaced.')}${block('Safer conceptual alternatives',x.alternatives,'No alternatives saved yet.')}<div class="muted small" style="margin-top:10px">Graph: ${x.graphNodes} nodes · ${x.graphEdges} connections · ${x.refs.length} sources · ${x.deep.length} deep-dive nodes</div></div>`;
}
async function saveIntelligenceSnapshot(){
  const x=await buildIntelligence();
  await put('events',{id:'evt_'+crypto.randomUUID(),projectId:currentProjectId,type:'intelligence_snapshot',at:new Date().toISOString(),summary:{confidence:x.confidence,next:x.next.slice(0,10),gaps:x.gaps,contradictions:x.contradictions,weakPatterns:x.weak.map(w=>w.text)}});
  toast('Intelligence snapshot saved to the investigation history.');
}
function renderDeepDive(refs){loadDeepRefs().then(()=>{if(!window.__deepResult)$('deepResult').innerHTML='';renderDeepTree();});}
$('deepRun').onclick=()=>{saveDeepDraft();runDeepDive(window.__deepFocus?.focus||'',window.__deepFocus?.kind||'root')};
$('deepSave').onclick=saveDeepCheckpoint;
$('deepQuestion').addEventListener('input',()=>{clearTimeout(window.__deepDraftTimer);window.__deepDraftTimer=setTimeout(saveDeepDraft,350)});
$('deepRef').addEventListener('change',()=>{window.__deepCurrentNodeId=null;window.__deepParentId=null;window.__deepResult=null;window.__deepFocus={focus:'',kind:'root'};saveDeepDraft()});
$('tabWorkspace').onclick=()=>setTab('workspace');$('tabDeepDive').onclick=()=>setTab('deepDive');$('navWorkspace').onclick=()=>setTab('workspace');$('navDeepDive').onclick=()=>setTab('deepDive');$('tabGraph').onclick=()=>setTab('graph');$('navGraph').onclick=()=>setTab('graph');$('tabIntelligence').onclick=()=>setTab('intelligence');$('navIntelligence').onclick=()=>setTab('intelligence');$('tabBrowse').onclick=()=>setTab('browse');$('tabEvidence').onclick=()=>setTab('evidence');$('tabArchive').onclick=()=>setTab('archive');$('tabLeads').onclick=()=>setTab('leads');$('tabIntelligence').onclick=()=>setTab('intelligence');$('navIntelligence').onclick=()=>setTab('intelligence');
const last=localStorage.getItem(URL_KEY)||'https://www.google.com';historyStack=[last];historyIndex=0;navigate(last,false);updateNav();openDB().then(migrateLegacy).then(migrateV19).then(migrateV20).then(migrateV21).then(migrateV22).then(migrateV23).then(backfillFingerprints).then(ensureProject).catch(e=>toast('Local archive unavailable: '+e.message));if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
